package Model;
// Generated Nov 17, 2016 7:58:09 PM by Hibernate Tools 5.2.0.Beta1

/**
 * BilldetailId generated by hbm2java
 */
public class BilldetailId implements java.io.Serializable {

	private int billid;
	private String productid;

	public BilldetailId() {
	}

	public BilldetailId(int billid, String productid) {
		this.billid = billid;
		this.productid = productid;
	}

	public int getBillid() {
		return this.billid;
	}

	public void setBillid(int billid) {
		this.billid = billid;
	}

	public String getProductid() {
		return this.productid;
	}

	public void setProductid(String productid) {
		this.productid = productid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BilldetailId))
			return false;
		BilldetailId castOther = (BilldetailId) other;

		return (this.getBillid() == castOther.getBillid())
				&& ((this.getProductid() == castOther.getProductid()) || (this.getProductid() != null
						&& castOther.getProductid() != null && this.getProductid().equals(castOther.getProductid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBillid();
		result = 37 * result + (getProductid() == null ? 0 : this.getProductid().hashCode());
		return result;
	}

}
