package Model;
// Generated Nov 20, 2016 11:37:27 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer customerid;
	private String customername;
	private String phone;
	private String address;
	private String customergroup;
	private String mail;

	public Customer() {
	}

	public Customer(String customername) {
		this.customername = customername;
	}

	public Customer(String customername, String phone, String address, String customergroup, String mail) {
		this.customername = customername;
		this.phone = phone;
		this.address = address;
		this.customergroup = customergroup;
		this.mail = mail;
	}

	public Integer getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	public String getCustomername() {
		return this.customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCustomergroup() {
		return this.customergroup;
	}

	public void setCustomergroup(String customergroup) {
		this.customergroup = customergroup;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

}
