package Model;
// Generated Nov 17, 2016 7:58:09 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Info generated by hbm2java
 */
public class Info implements java.io.Serializable {

	private Integer infoid;
	private String infohead;
	private String infobody;
	private String date;
	private String labelimg;

	public Info() {
	}

	public Info(String infohead, String infobody, String date, String labelimg) {
		this.infohead = infohead;
		this.infobody = infobody;
		this.date = date;
		this.labelimg = labelimg;
	}

	public Integer getInfoid() {
		return this.infoid;
	}

	public void setInfoid(Integer infoid) {
		this.infoid = infoid;
	}

	public String getInfohead() {
		return this.infohead;
	}

	public void setInfohead(String infohead) {
		this.infohead = infohead;
	}

	public String getInfobody() {
		return this.infobody;
	}

	public void setInfobody(String infobody) {
		this.infobody = infobody;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getLabelimg() {
		return this.labelimg;
	}

	public void setLabelimg(String labelimg) {
		this.labelimg = labelimg;
	}

}
