package Model;
// Generated Oct 29, 2016 7:48:45 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * ProductgroupId generated by hbm2java
 */
public class ProductgroupId implements java.io.Serializable {

	private int pgrouppid;
	private String pgroupname;
	private String pgroupnote;

	public ProductgroupId() {
	}

	public ProductgroupId(int pgrouppid, String pgroupname) {
		this.pgrouppid = pgrouppid;
		this.pgroupname = pgroupname;
	}

	public ProductgroupId(int pgrouppid, String pgroupname, String pgroupnote) {
		this.pgrouppid = pgrouppid;
		this.pgroupname = pgroupname;
		this.pgroupnote = pgroupnote;
	}

	public int getPgrouppid() {
		return this.pgrouppid;
	}

	public void setPgrouppid(int pgrouppid) {
		this.pgrouppid = pgrouppid;
	}

	public String getPgroupname() {
		return this.pgroupname;
	}

	public void setPgroupname(String pgroupname) {
		this.pgroupname = pgroupname;
	}

	public String getPgroupnote() {
		return this.pgroupnote;
	}

	public void setPgroupnote(String pgroupnote) {
		this.pgroupnote = pgroupnote;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductgroupId))
			return false;
		ProductgroupId castOther = (ProductgroupId) other;

		return (this.getPgrouppid() == castOther.getPgrouppid())
				&& ((this.getPgroupname() == castOther.getPgroupname()) || (this.getPgroupname() != null
						&& castOther.getPgroupname() != null && this.getPgroupname().equals(castOther.getPgroupname())))
				&& ((this.getPgroupnote() == castOther.getPgroupnote())
						|| (this.getPgroupnote() != null && castOther.getPgroupnote() != null
								&& this.getPgroupnote().equals(castOther.getPgroupnote())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPgrouppid();
		result = 37 * result + (getPgroupname() == null ? 0 : this.getPgroupname().hashCode());
		result = 37 * result + (getPgroupnote() == null ? 0 : this.getPgroupnote().hashCode());
		return result;
	}

}
