package Model;
// Generated Oct 29, 2016 8:28:24 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Suplier generated by hbm2java
 */
public class Suplier implements java.io.Serializable {

	private String suplierid;
	private String supliername;
	private String phone;
	private String address;
	private String supliergroup;
	private String mail;

	public Suplier() {
	}

	public Suplier(String suplierid, String supliername, String phone, String address, String mail) {
		this.suplierid = suplierid;
		this.supliername = supliername;
		this.phone = phone;
		this.address = address;
		this.mail = mail;
	}

	public Suplier(String suplierid, String supliername, String phone, String address, String supliergroup,
			String mail) {
		this.suplierid = suplierid;
		this.supliername = supliername;
		this.phone = phone;
		this.address = address;
		this.supliergroup = supliergroup;
		this.mail = mail;
	}

	public String getSuplierid() {
		return this.suplierid;
	}

	public void setSuplierid(String suplierid) {
		this.suplierid = suplierid;
	}

	public String getSupliername() {
		return this.supliername;
	}

	public void setSupliername(String supliername) {
		this.supliername = supliername;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSupliergroup() {
		return this.supliergroup;
	}

	public void setSupliergroup(String supliergroup) {
		this.supliergroup = supliergroup;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

}
