package Model;
// Generated Nov 17, 2016 7:58:09 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Warehouse generated by hbm2java
 */
public class Warehouse implements java.io.Serializable {

	private Integer wid;
	private String supilerid;
	private int pay;
	private int total;
	private Date day;
	private String creator;
	private String status;
	private String note;
	private int tax;
	private int excess;

	public Warehouse() {
	}

	public Warehouse(String supilerid, int pay, int total, Date day, String creator, String status, String note,
			int tax, int excess) {
		this.supilerid = supilerid;
		this.pay = pay;
		this.total = total;
		this.day = day;
		this.creator = creator;
		this.status = status;
		this.note = note;
		this.tax = tax;
		this.excess = excess;
	}

	public Integer getWid() {
		return this.wid;
	}

	public void setWid(Integer wid) {
		this.wid = wid;
	}

	public String getSupilerid() {
		return this.supilerid;
	}

	public void setSupilerid(String supilerid) {
		this.supilerid = supilerid;
	}

	public int getPay() {
		return this.pay;
	}

	public void setPay(int pay) {
		this.pay = pay;
	}

	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public int getTax() {
		return this.tax;
	}

	public void setTax(int tax) {
		this.tax = tax;
	}

	public int getExcess() {
		return this.excess;
	}

	public void setExcess(int excess) {
		this.excess = excess;
	}

}
