"Redo" description="Redo the last operation" category="_bU7tWq99EeadAOq7znZXOA"/>
  <commands xmi:id="_bU7GNK99EeadAOq7znZXOA" elementId="org.eclipse.wst.server.launchShortcut.debug" commandName="Debug on Server" description="Debug the current selection on a server" category="_bU7tZa99EeadAOq7znZXOA"/>
  <commands xmi:id="_bU7GNa99EeadAOq7znZXOA" elementId="org.eclipse.m2e.editor.RenameArtifactAction" commandName="Rename Maven Artifact..." category="_bU7tb699EeadAOq7znZXOA"/>
  <commands xmi:id="_bU7GNq99EeadAOq7znZXOA" elementId="org.eclipse.ui.navigate.selectWorkingSets" commandName="Select Working Sets" description="Select the working sets that are applicable for this window." category="_bU7tY699EeadAOq7znZXOA"/>
  <commands xmi:id="_bU7GN699EeadAOq7znZXOA" elementId="org.eclipse.datatools.sqltools.sqleditor.ExecuteSQLAction" commandName="Execute All" category="_bU7tha99EeadAOq7znZXOA"/>
  <commands xmi:id="_bU7GOK99EeadAOq7znZXOA" elementId="org.eclipse.jdt.ui.edit.text.java.rename.element" commandName="Rename - Refactoring " description="Rename the selected element" category="_bU7tfq99EeadAOq7znZXOA"/>
  <commands xmi:id="_bU7qgK99EeadAOq7znZXOA" elementId="org.eclipse.pde.api.tools.ui.remove.filters" commandName="Remove &amp;API Problem Filters..." description="Remove API problem filters for this project" category="_bU7tb699EeadAOq7znZXOA"/>
  <commands xmi:id="_bU7qga99EeadAOq7znZXOA" elementId="org.eclipse.tm.terminal.view.ui.command.newview" commandName="New Terminal View" category="_bU7teq99EeadAOq7znZXOA"/>
  <commands xmi:id="_bU7qgq99EeadAOq7znZXOA" elementId="org.eclipse.jdt.ui.edit.text.java.externalize.strings" commandName="Externalize Strings" description="Finds all strings that are not externalized and moves them into a separate property file" category="_bU7tia99EeadAOq7znZXOA"/>
  <commands xmi:id="_bU7qg699EeadAOq7znZXOA" elementId="org.eclipse.wst.jsdt.ui.correction.extractConstant.assist" commandName="Quick Assist - Extract constant" description="Invokes quick assist and selects 'Extra